### ISSUE TITLE
package.json settings

### ISSUE THREAD

**Issue by cojovi** [PixelRocket-Shop/oldskool-html-bootstrap#2]
are there specific versions for : babel-minify-webpack-plugin, webpack, babel-loader ?
im having some issues trying to get it running, im sure tehre have been many updates since this was released.

any intel here?

**Comment by pixelrocket66** [comment]
Hey, no idea on the specific versions, but given that I released this two years ago, I think you'll struggle to get this working. If you only want to use the code, I'd suggest using the code in the dist folder. Otherwise, if you need to the source code working locally, you can start by updating all packages and seeing what error messages you get. For what it's worth, I am planning on a full update to the latest Bootstrap version, but I won't have time until the new year to do the work.
